spring:
  datasource:
    url: jdbc:mysql://43.138.64.174:33070/opt_helper
    username: DB_root
    password: Paab7ZYs5tThhJFK
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    port: 63800
    host: 43.138.64.174
    password: qwertyuiop
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000

server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  mapper-locations:
    classpath:/mapper/*.xml